<?php
require_once ("model/permisa.class.php");
/**
* Skup svih relacija
*
* 1 - ima primjerak
* 2 - ima podvrstu
* 3 - se sastoji od
* 4 - služi za
* 5 - vrši
**/
$relacije[] = new Relacija ("ima primjerak"); 
$relacije[] = new Relacija ("ima podvrstu"); 
$relacije[] = new Relacija ("se sastoji od"); 
$relacije[] = new Relacija ("služi za"); 
$relacije[] = new Relacija ("vrši");
$relacije[] = new Relacija ("upravlja s"); 
$relacije[] = new Relacija ("ima"); 
$relacije[] = new Relacija ("prevodi"); 
/**
* Skup svih relacija
**/

/*0*/$koncepti[] = new Koncept ("Računalni sustav"); 
/*1*/$koncepti[] = new Koncept ("Temeljna funkcija računala");
/*2*/$koncepti[] = new Koncept ("Tehnička podrška");
/*3*/$koncepti[] = new Koncept ("Obrada podataka");
/*4*/$koncepti[] = new Koncept ("Prikaz podataka");
/*5*/$koncepti[] = new Koncept ("Upravljanje podataka");
/*6*/$koncepti[] = new Koncept ("Pohrana podataka");
/*7*/$koncepti[] = new Koncept ("Unos podataka");
/*8*/$koncepti[] = new Koncept ("Model računalnog sustava");
/*9*/$koncepti[] = new Koncept ("Ulazna jedinica");
/*10*/$koncepti[] = new Koncept ("Izlazna jedinica");
/*11*/$koncepti[] = new Koncept ("Tipkovnica");
/*12*/$koncepti[] = new Koncept ("Miš");
/*13*/$koncepti[] = new Koncept ("Monitor");
/*14*/$koncepti[] = new Koncept ("Štampač");
/*15*/$koncepti[] = new Koncept ("Centralna jedinica");
/*16*/$koncepti[] = new Koncept ("Računalo");
/*17*/$koncepti[] = new Koncept ("Centralna procesorska jedinica");
/*18*/$koncepti[] = new Koncept ("Upravljačka jedinica");
/*19*/$koncepti[] = new Koncept ("Aritmetičko logička jedinica");
/*20*/$koncepti[] = new Koncept ("Instrukcija");
/*21*/$koncepti[] = new Koncept ("Podatak");
/*22*/$koncepti[] = new Koncept ("Operacija");
/*23*/$koncepti[] = new Koncept ("Informacija");
/*24*/$koncepti[] = new Koncept ("Značenje");
/*25*/$koncepti[] = new Koncept ("Aritmetička operacija");
/*26*/$koncepti[] = new Koncept ("Zbrajanje");
/*27*/$koncepti[] = new Koncept ("Oduzimanje");
/*28*/$koncepti[] = new Koncept ("Upravljačka jedinica");
/*29*/$koncepti[] = new Koncept ("Logička operacija");
/*30*/$koncepti[] = new Koncept ("Upravljačka jedinica");
/*31*/$koncepti[] = new Koncept ("Disjunkcija");
/*32*/$koncepti[] = new Koncept ("Konjukcija");
/*33*/$koncepti[] = new Koncept ("Negacija");
/*34*/$koncepti[] = new Koncept ("Logički sklop");
/*35*/$koncepti[] = new Koncept ("Ili sklop");
/*36*/$koncepti[] = new Koncept ("Ni sklop");
/*37*/$koncepti[] = new Koncept ("Nili sklop");
/*38*/$koncepti[] = new Koncept ("Ne sklop");
/*39*/$koncepti[] = new Koncept ("I sklop");
/*40*/$koncepti[] = new Koncept ("Tehnička podrška");
/*41*/$koncepti[] = new Koncept ("Centralna jedinica");
/*42*/$koncepti[] = new Koncept ("Računalo");
/*43*/$koncepti[] = new Koncept ("Memorija");
/*44*/$koncepti[] = new Koncept ("Masovna memorija");
/*45*/$koncepti[] = new Koncept ("Radna memorija");
/*46*/$koncepti[] = new Koncept ("Disketa");
/*47*/$koncepti[] = new Koncept ("Kompaktni disk");
/*48*/$koncepti[] = new Koncept ("Radna memorija");
/*49*/$koncepti[] = new Koncept ("RAM");
/*50*/$koncepti[] = new Koncept ("ROM");
/*51*/$koncepti[] = new Koncept ("Uređaj za komunikaciju");
/*52*/$koncepti[] = new Koncept ("Mrežna kartica");
/*53*/$koncepti[] = new Koncept ("Prijenos podataka");
/*54*/$koncepti[] = new Koncept ("Modem");
/*55*/$koncepti[] = new Koncept ("Paralelni prijenos podataka");
/*56*/$koncepti[] = new Koncept ("Serijski prijenos podataka");
/*57*/$koncepti[] = new Koncept ("Programska podrška");
/*58*/$koncepti[] = new Koncept ("Aplikacijska programska podrška");
/*59*/$koncepti[] = new Koncept ("Sistemska programska podrška");
/*60*/$koncepti[] = new Koncept ("Jezični prevoditelji");
/*61*/$koncepti[] = new Koncept ("Operacijski sustav");
/*62*/$koncepti[] = new Koncept ("Uslužni programi");
/*63*/$koncepti[] = new Koncept ("DOS");
/*64*/$koncepti[] = new Koncept ("Windows");
/*65*/$koncepti[] = new Koncept ("Unix");
/*66*/$koncepti[] = new Koncept ("Programski jezik visoke razine");
/*67*/$koncepti[] = new Koncept ("Programski jezik niske razine");
/*68*/$koncepti[] = new Koncept ("Asembler");
/*69*/$koncepti[] = new Koncept ("C");
/*70*/$koncepti[] = new Koncept ("Pascal");
/*71*/$koncepti[] = new Koncept ("Fortran");
/*72*/$koncepti[] = new Koncept ("Basic");
/*73*/$koncepti[] = new Koncept ("Dekadski brojevni sustav");
/*74*/$koncepti[] = new Koncept ("Binarni brojevni sustav");
/*75*/$koncepti[] = new Koncept ("Oktalni brojevni sustav");
/*76*/$koncepti[] = new Koncept ("Heksadecimalni brojevni sustav");
/*77*/$koncepti[] = new Koncept ("Tvrdi disk");
/*78*/$koncepti[] = new Koncept ("Kompilator");
/*79*/$koncepti[] = new Koncept ("Interpretator");
/*80*/$koncepti[] = new Koncept ("Programski jezik");
/*81*/$koncepti[] = new Koncept ("Brojevni sustav");

$permise[] = new permisa($koncepti[0], $relacije[4], $koncepti[1]);
$permise[] = new permisa($koncepti[0], $relacije[2], $koncepti[2]);
$permise[] = new permisa($koncepti[1], $relacije[0], $koncepti[3]);
$permise[] = new permisa($koncepti[1], $relacije[0], $koncepti[4]);
$permise[] = new permisa($koncepti[1], $relacije[0], $koncepti[7]);
$permise[] = new permisa($koncepti[3], $relacije[2], $koncepti[5]);
$permise[] = new permisa($koncepti[3], $relacije[2], $koncepti[6]);
$permise[] = new permisa($koncepti[8], $relacije[2], $koncepti[9]);
$permise[] = new permisa($koncepti[8], $relacije[2], $koncepti[10]);
$permise[] = new permisa($koncepti[9], $relacije[3], $koncepti[7]);
$permise[] = new permisa($koncepti[9], $relacije[1], $koncepti[11]);
$permise[] = new permisa($koncepti[9], $relacije[1], $koncepti[12]);
$permise[] = new permisa($koncepti[10], $relacije[3], $koncepti[4]);
$permise[] = new permisa($koncepti[10], $relacije[1], $koncepti[13]);
$permise[] = new permisa($koncepti[10], $relacije[1], $koncepti[14]);
$permise[] = new permisa($koncepti[8], $relacije[2], $koncepti[15]);
$permise[] = new permisa($koncepti[15], $relacije[2], $koncepti[16]);
$permise[] = new permisa($koncepti[15], $relacije[2], $koncepti[44]);
$permise[] = new permisa($koncepti[16], $relacije[2], $koncepti[17]);
$permise[] = new permisa($koncepti[16], $relacije[2], $koncepti[45]);
$permise[] = new permisa($koncepti[17], $relacije[2], $koncepti[30]);
$permise[] = new permisa($koncepti[30], $relacije[5], $koncepti[20]);
$permise[] = new permisa($koncepti[17], $relacije[2], $koncepti[19]);
$permise[] = new permisa($koncepti[20], $relacije[2], $koncepti[21]);
$permise[] = new permisa($koncepti[20], $relacije[2], $koncepti[22]);
$permise[] = new permisa($koncepti[21], $relacije[1], $koncepti[23]);
$permise[] = new permisa($koncepti[23], $relacije[6], $koncepti[24]);
$permise[] = new permisa($koncepti[22], $relacije[1], $koncepti[25]);
$permise[] = new permisa($koncepti[25], $relacije[0], $koncepti[26]);
$permise[] = new permisa($koncepti[25], $relacije[0], $koncepti[27]);
$permise[] = new permisa($koncepti[22], $relacije[1], $koncepti[29]);
$permise[] = new permisa($koncepti[19], $relacije[4], $koncepti[25]);
$permise[] = new permisa($koncepti[22], $relacije[4], $koncepti[29]);
$permise[] = new permisa($koncepti[29], $relacije[0], $koncepti[31]);
$permise[] = new permisa($koncepti[29], $relacije[0], $koncepti[32]);
$permise[] = new permisa($koncepti[29], $relacije[0], $koncepti[33]);
$permise[] = new permisa($koncepti[45], $relacije[1], $koncepti[49]);
$permise[] = new permisa($koncepti[45], $relacije[1], $koncepti[50]);
$permise[] = new permisa($koncepti[44], $relacije[1], $koncepti[46]);
$permise[] = new permisa($koncepti[44], $relacije[1], $koncepti[47]);
$permise[] = new permisa($koncepti[44], $relacije[1], $koncepti[78]);
$permise[] = new permisa($koncepti[43], $relacije[3], $koncepti[6]);
$permise[] = new permisa($koncepti[43], $relacije[1], $koncepti[44]);
$permise[] = new permisa($koncepti[43], $relacije[1], $koncepti[45]);
$permise[] = new permisa($koncepti[2], $relacije[1], $koncepti[9]);
$permise[] = new permisa($koncepti[2], $relacije[1], $koncepti[10]);
$permise[] = new permisa($koncepti[2], $relacije[1], $koncepti[15]);
$permise[] = new permisa($koncepti[2], $relacije[1], $koncepti[43]);
$permise[] = new permisa($koncepti[2], $relacije[1], $koncepti[51]);
$permise[] = new permisa($koncepti[51], $relacije[1], $koncepti[54]);
$permise[] = new permisa($koncepti[51], $relacije[1], $koncepti[52]);
$permise[] = new permisa($koncepti[51], $relacije[3], $koncepti[53]);
$permise[] = new permisa($koncepti[53], $relacije[1], $koncepti[55]);
$permise[] = new permisa($koncepti[53], $relacije[1], $koncepti[56]);
$permise[] = new permisa($koncepti[54], $relacije[4], $koncepti[56]);
$permise[] = new permisa($koncepti[34], $relacije[0], $koncepti[35]);
$permise[] = new permisa($koncepti[34], $relacije[0], $koncepti[36]);
$permise[] = new permisa($koncepti[34], $relacije[0], $koncepti[37]);
$permise[] = new permisa($koncepti[34], $relacije[0], $koncepti[38]);
$permise[] = new permisa($koncepti[34], $relacije[0], $koncepti[39]);
$permise[] = new permisa($koncepti[34], $relacije[4], $koncepti[29]);
$permise[] = new permisa($koncepti[35], $relacije[4], $koncepti[31]);
$permise[] = new permisa($koncepti[36], $relacije[4], $koncepti[32]);
$permise[] = new permisa($koncepti[36], $relacije[4], $koncepti[33]);
$permise[] = new permisa($koncepti[37], $relacije[4], $koncepti[31]);
$permise[] = new permisa($koncepti[37], $relacije[4], $koncepti[33]);
$permise[] = new permisa($koncepti[38], $relacije[4], $koncepti[33]);
$permise[] = new permisa($koncepti[39], $relacije[4], $koncepti[32]);
$permise[] = new permisa($koncepti[0], $relacije[2], $koncepti[57]);
$permise[] = new permisa($koncepti[57], $relacije[1], $koncepti[58]);
$permise[] = new permisa($koncepti[57], $relacije[1], $koncepti[59]);
$permise[] = new permisa($koncepti[59], $relacije[1], $koncepti[60]);
$permise[] = new permisa($koncepti[59], $relacije[1], $koncepti[61]);
$permise[] = new permisa($koncepti[59], $relacije[1], $koncepti[62]);
$permise[] = new permisa($koncepti[60], $relacije[1], $koncepti[79]);
$permise[] = new permisa($koncepti[60], $relacije[1], $koncepti[78]);
$permise[] = new permisa($koncepti[60], $relacije[7], $koncepti[66]);
$permise[] = new permisa($koncepti[61], $relacije[0], $koncepti[63]);
$permise[] = new permisa($koncepti[61], $relacije[0], $koncepti[64]);
$permise[] = new permisa($koncepti[61], $relacije[0], $koncepti[65]);
$permise[] = new permisa($koncepti[80], $relacije[1], $koncepti[66]);
$permise[] = new permisa($koncepti[80], $relacije[1], $koncepti[67]);
$permise[] = new permisa($koncepti[66], $relacije[1], $koncepti[68]);
$permise[] = new permisa($koncepti[67], $relacije[0], $koncepti[72]);
$permise[] = new permisa($koncepti[67], $relacije[0], $koncepti[71]);
$permise[] = new permisa($koncepti[67], $relacije[0], $koncepti[70]);
$permise[] = new permisa($koncepti[67], $relacije[0], $koncepti[69]);
$permise[] = new permisa($koncepti[81], $relacije[0], $koncepti[73]);
$permise[] = new permisa($koncepti[81], $relacije[0], $koncepti[74]);
$permise[] = new permisa($koncepti[81], $relacije[0], $koncepti[75]);
$permise[] = new permisa($koncepti[81], $relacije[0], $koncepti[76]);


var_dump ($permise);
/*Primjer pitanja : Koji Logički sklop izvršava Logička operacija Disjunkcija -> Ili sklop */